// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQZIP_IznoiDMctZDsDE72JBlGx1JFbRQ',
    appId: '1:1084462734057:web:ac0b86d746e07d2c5c2e78',
    messagingSenderId: '1084462734057',
    projectId: 'todo-list-4a107',
    authDomain: 'todo-list-4a107.firebaseapp.com',
    storageBucket: 'todo-list-4a107.appspot.com',
    measurementId: 'G-S1ZER4YNP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAun1mP1lhp2cWFI2xJ2pSKK9XfxuShp9k',
    appId: '1:1084462734057:android:19df64ce3dbb7cd55c2e78',
    messagingSenderId: '1084462734057',
    projectId: 'todo-list-4a107',
    storageBucket: 'todo-list-4a107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgvOldxrMcmmiNtBKRng9zrclHVq26oTU',
    appId: '1:1084462734057:ios:56c9a281a9c9080a5c2e78',
    messagingSenderId: '1084462734057',
    projectId: 'todo-list-4a107',
    storageBucket: 'todo-list-4a107.appspot.com',
    iosBundleId: 'com.example.lab4Todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgvOldxrMcmmiNtBKRng9zrclHVq26oTU',
    appId: '1:1084462734057:ios:56c9a281a9c9080a5c2e78',
    messagingSenderId: '1084462734057',
    projectId: 'todo-list-4a107',
    storageBucket: 'todo-list-4a107.appspot.com',
    iosBundleId: 'com.example.lab4Todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQZIP_IznoiDMctZDsDE72JBlGx1JFbRQ',
    appId: '1:1084462734057:web:1c026473d2e71ce65c2e78',
    messagingSenderId: '1084462734057',
    projectId: 'todo-list-4a107',
    authDomain: 'todo-list-4a107.firebaseapp.com',
    storageBucket: 'todo-list-4a107.appspot.com',
    measurementId: 'G-L9VY63RP00',
  );
}
